# Generated by Django 3.1 on 2021-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
