# Generated by Django 3.1 on 2021-04-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='BloodBank',
        ),
    ]
