# Generated by Django 3.1 on 2021-04-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20210427_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_pos', models.IntegerField(default=0)),
                ('a_neg', models.IntegerField(default=0)),
                ('b_pos', models.IntegerField(default=0)),
                ('b_neg', models.IntegerField(default=0)),
                ('o_pos', models.IntegerField(default=0)),
                ('o_neg', models.IntegerField(default=0)),
                ('ab_pos', models.IntegerField(default=0)),
                ('ab_neg', models.IntegerField(default=0)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodbank')),
            ],
        ),
    ]
